/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package zoologico.view;

/**
 *
 * @author layonel
 */
public class VentanaPricipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPricipal
     */
    private VentanaViewAnimals VentViewAnimals;

    public void setVentViewAnimals(VentanaViewAnimals VentViewAnimals) {
        this.VentViewAnimals = VentViewAnimals;
    }
    
    public VentanaPricipal() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        group = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        verAnimales = new javax.swing.JButton();
        verHabitats = new javax.swing.JButton();
        crearHabitat = new javax.swing.JButton();
        addAnimal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ZOOLOGICO");
        jLabel1.setToolTipText("");

        verAnimales.setText("Ver Animales");
        verAnimales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verAnimalesActionPerformed(evt);
            }
        });

        verHabitats.setText("Ver Habitats");
        verHabitats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verHabitatsActionPerformed(evt);
            }
        });

        crearHabitat.setText("Crear Habitat");
        crearHabitat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearHabitatActionPerformed(evt);
            }
        });

        addAnimal.setText("Añadir Animal");
        addAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAnimalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(crearHabitat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(verAnimales, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(verHabitats, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addAnimal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(56, 56, 56)
                .addComponent(verAnimales)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(verHabitats)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(crearHabitat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addAnimal)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void verAnimalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verAnimalesActionPerformed
        VentanaViewAnimals VentViewAni = new VentanaViewAnimals();
       
        VentViewAni.setLocationRelativeTo(null);
        VentViewAni.setVisible(true);
        VentViewAni.setSize(800, 500);
        VentViewAni.setLocation(0, 0);
        this.setVisible(false);
        System.out.println("Viendo Animales...");
    }//GEN-LAST:event_verAnimalesActionPerformed
    
    private void verHabitatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verHabitatsActionPerformed
        System.out.println("Viendo Habitats...");
    }//GEN-LAST:event_verHabitatsActionPerformed

    private void crearHabitatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearHabitatActionPerformed
        System.out.println("Creando Habitats...");
    }//GEN-LAST:event_crearHabitatActionPerformed

    private void addAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAnimalActionPerformed
        System.out.println("Añadiendo Animales...");
    }//GEN-LAST:event_addAnimalActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAnimal;
    private javax.swing.JButton crearHabitat;
    private javax.swing.ButtonGroup group;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton verAnimales;
    private javax.swing.JButton verHabitats;
    // End of variables declaration//GEN-END:variables
}
